# Generated by Django 4.1.5 on 2023-01-24 09:20

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="blog/default.jpg", upload_to=blog.models.upload_to
            ),
        ),
    ]
